CREATE DATABASE BLOG;


CREATE TABLE PERMISSOES(
	ID_PERMISSAO INT NOT NULL PRIMARY KEY,
	NOME_PERMISSAO VARCHAR(15) NOT NULL,
	DESCRICAO_PERMISSAO VARCHAR(255) NOT NULL
);


CREATE TABLE PERFIS(
	ID_PERFIL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME_PERFIL VARCHAR(10),
	PERMISSOES_PERFIL INT FOREIGN KEY REFERENCES PERMISSOES(ID_PERMISSAO)
);


CREATE TABLE USUARIOS(
	ID_USUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME_USUARIO VARCHAR(200) NOT NULL,
	PERFIL_USUARIO FOREIGN KEY REFERENCES PERFIS(ID_PERFIL)
);

CREATE TABLE POST(
	ID_POST INT NOT NULL PRIMARY KEY,
	USUARIO_RESPONSAVEL INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID_USUARIO)
);

--- EU AAAAAAAAAAAAAACHO QUE TA CERTO