<?php



	/*
	* AQUI FAZEMOS A CONEXAO COM BANCO, ONDE VOCÊ PASSA DENTRO DA QUERY MYSQLI_CONNECT OS DADOS
	* HOST ONDE ESTA O BANCO, USUARIO QUE VAI FAZER O ACESS, A SENHA E O BANCO EM QUE VAI CONECTAR
	* A PARTIR DO PHP 7.1 É EXIGIDO QUE VOCÊ TENHA ESTA ESPECIE DE CHAVE CONEXAO QUE EU NOMIEI DE 
	* $conexao ;)
	*
	* PHP É UMA LINGUAGEM BACK END, QUE RODA NO SERVIDOR, COMO ESTOU NO MEU COMPUTADOR TEORICAMENTE ISTO
	* NAO SERIA POSSIVEL, PARA ISTO USAMOS O XAMPP --  BASICAMENTE VOCÊ DEVE DAR PLAY NO APACHE E NO MYSQL
	*
	* PARA ADMINSTRAR O BANCO EU USO O HEIGH SQL, ENTAO VOU CRIAR O BANCO LA PARA CONECTAR O PHP E BUSCAR OS DADOS
	* PODEMOS JA TESTAR CONEXAO COM BANCO DE UMA VEZ
	*/



	// CREDENCIAS PARA CONEXAO


	// COMO ESTOU USANDO A MAQUINA LOCAL, MEU HOST É O "LOCALHOST"
	$host = "localhost";

	// POR PADRAO OP MY SQL TEM O USUARIO ROOT 
	$usuario = "root";

	// O USUARIO ROOT NÃO TEM SENHA, MUITO CUIDADO COM ISSO QUANDO FOR FAZER UMA APLICAÇÃO HOSPEDADA
	$pass = "";

	// O BANCO DE DADOS SERÁ O QUE VAMOS CRIAR AGORA
	$bd = "BLOG";

	// CRIACAO DA CONEXAO

	$conexao = mysqli_connect($host, $usuario, $pass, $bd);




	// TESTE ONDE VERIFICA SE TEM OU NAO CONEXAO
	// A CONEXAO FUNCIONOU 
	// AGORA VAMOS INSERIR DADOS PARA EXTRACAO DO BANCO
	if (!$conexao) {
		echo "Erro de conexao";
	}else{
		echo "Conectado com sucesso<br><br>";
	}



	// AGORA EU LEMBRAR COMO FAZ ISSO KKKKKKKKKKKKKKKKKKKKKKKK

	// NAO DEU ERRO É UM OTIMO SINAL, AGORA VAMOS MANDAR ESCREVER O DADOS PRA VER SE 
	// CHEGOU DIREITO


	// DONE ! ESTAMOS CONECTANDO E BUSCANO DADOS COM SUCESSO

	// EXPLICANDO ESTE CODIGO

	// MYSQLI_QUERY É RESPONSAVEL POR INSERIR A QUERY NO BANCO, A PARTIR DO PHP 7.1
	// VOCE PRECISA PASSAR A CONEXAO E ENTAO A QUERY IGUAL ESTA ABAIXO

	$query = mysqli_query($conexao, "SELECT * FROM PERMISSOES WHERE ID_PERMISSAO = 1");


	// O RESULTADO DA QUERY ACIMA DEVE SER INSERIDA NO COMANDO mysqli_fetch_array ONDE OS DADOS
	// SAO GERADOS EM FORMA DE ARRAY
	$dadoParaUsar =  mysqli_fetch_array($query);	


	// TENDO OS DADOS EM FORMA DE ARRAY NA VARIAVEL QUE VOCÊ DEFINIU, BASTA BUSCAR PELO NOME
	// DO CAMPO NO SQL COMO FOI FEITO ABAIXO
	echo $dadoParaUsar['DESCRICAO_PERMISSAO'];

	// DEU PRA PEGAR ?



	// VOU SUBIR ESTES CODIGOS PARA O GIT HUB, PODE PEGAR E BAGULHAR ELE LA
	// VOU PARAR AQUI E VOLTO EM BREVE ATE ESTE SISTEMA ESTAR COMPLETO E PRONTO 
	// PRA USO
	//  ALGUMA DUVIDA ANTES DE EU SAIR ?




	/*
		PORQUE FAZER ISSO TUDO E NAO USAR WORDPRESS ?

		-- DESEMPENHO
		-- SEGURANÇA
		-- SEO
		-- CONHECER O PROPRIO CODIGO
		-- EVITAR CONFLITOS ENTRE PLUGINS 

		
		DESEMPNEHO: O DESEMPNEHO DO WORDPRESS E BEM INFERIOR AO DE UMA APLICAÇÃO FEITA A MAO
		PARA UMA NECESSIDADE NA HORA, SIM, MUITO BOM E FUNCIONAL, MAS NÃO TERA
		O MESMO DESEMPENHO POR CAUSA DA QUANTIADE DE PACOTES QUE ELE TEM

		SEGURANÇA: QUALQUER SITE PODE SER FACILMENTE VISTO COMO FEITO EM WORDPRESS
		ELE PODE TAMBEM SER ACESSO DE QUALQUER LUGAR, SO COLOCAR WP-ADMIN APOS A URL
		PRINCIPAL


		SEO: O SEO DE UM SITE FEITO A MAO TEM MAIS RESULTADOS, PORQUE SITES FEITOS EM WORDPRESS
		CARREGAM COM SI O SEO DA APLICACAO E DO WORPRESS JUNTOS, VOCÊ PERCEBE ISSO VENDO O CODIGO
		FONTE, EXISTE MAIS INFORMAÇÕES SOBRE A PLATAFORMA DO QUE O PROPRIO SITE DO CLIENTE..


		CONHECER O PROPRIO CODIGO: QUANDO VOCÊ TEM QUE DAR MANUTENÇÃO E FAZER ALTERAÇÃO
		CONHECER SEU PADRAO DE TRABALHO E MUITO BOM, POREM, QUANDO VOCÊ TRABALHA COM WORPRESS
		VOCÊ NAO TEM UM PADRAO DEFINIDO, CADA PLUGIN OU TEMA TEM SEU PADRAO, OU SEJA VOCÊ TEM QUE FICAR
		SE ADAPATANDO A ISTO

		EVITAR CONFLITOS: CADA PLUGIN TEM UMA FINALIDADE, MAS ALGUNS BUGAM ENTRE EELES, E CONTRAOLAR ISSO
		E MUITO DIFICIL E COMPLICADO, AINDA MAIS SE SUA APLICAÇÃO FOR CRESCER ALGUM DIA

		E ESTES SAO UNS DOS MOTIVOS PARA FAZER NA UNHA E NAO USAR WORDPRESS

	*/










?>